[package]
name = "rfs"
version = "0.1.0"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"
license = "MIT"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "rfs-client", "rfs-server"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
nix = "0.17"
libc = "0.2"
path-clean = "0.1"
futures = "0.3"
tonic = { version = "0.1", features = ["transport", "tls"] }
prost = "0.6"
prost-types = "0.6"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = "0.4"
thiserror = "1.0"
tower = "0.3"
anyhow = "1.0"
lazy_static = "1.4"

[dependencies.fuse]
branch = "master"
git = "https://github.com/Sherlock-Holo/fuse-rs"
features = ["posix-lock"]

[dependencies.tokio]
version = "0.2"
features = [
"uds",
"stream",
"blocking",
"fs",
"signal",
"io-util",
"sync",
"macros"
]

[dev-dependencies]
tempfile = "3.1"

[build-dependencies]
tonic-build = "0.1"
rustversion = "1.0"
