[package]
name = "rfs"
version = "0.1.0"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"
license = "MIT"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "rfs-client", "rfs-server"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
nix = "0.17"
libc = "0.2"
path-clean = "0.1"
futures-util = "0.3"
tonic = { version = "0.1", features = ["transport", "tls", "tls-roots"] }
prost = "0.6"
prost-types = "0.6"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = "0.4"
thiserror = "1.0"
tower = "0.3"
anyhow = "1.0"
async-notify = "0.1"
async-signals = "0.1.0"
tokio = "0.2"

[profile.release]
lto = true

[dependencies.fuse]
branch = "master"
git = "https://github.com/Sherlock-Holo/fuse-rs"
features = ["posix-lock"]

[dependencies.async-std]
version = "1.5"
features = ["attributes"]

[dev-dependencies]
tempfile = "3.1"

[build-dependencies]
tonic-build = "0.1"
