[package]
name = "rfs-client"
version = "0.2.1"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfs = { path = ".." }

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.3"
anyhow = "1.0"
log = "0.4"
tonic = { version = "0.2", features = ["tls"] }
futures = "0.3"
lazy_static = "1"
nix = "0.17"

[dependencies.tokio]
version = "0.2"
features = ["rt-threaded"]

[dependencies.async-std]
version = "1.5"
features = ["attributes"]
